#!/bin/sh
MAPS=/proc/sys/vm/mmap_min_addr

EXPECTED="$1"
PREVIOUS=$(cat $MAPS 2>/dev/null || echo 0)

if [ "$EXPECTED" != "$PREVIOUS" ]; then
    echo "Yikes!  mmap_min_addr did not start as $EXPECTED (saw $PREVIOUS)" >&2
    exit 255
fi

echo 0 > $MAPS
sudo -u $SUDO_USER ./low-mmap $EXPECTED
rc=$?
if [ -r $MAPS ]; then
    echo $PREVIOUS > $MAPS
fi
exit $rc
