#!/bin/sh
################################################################################
# Copyright 2013 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 2.1.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Jamie Strandboge <jamie@canonical.com>
################################################################################

set -e

# Failure counter
F_I=0

# Success counter
S_I=0

# Total counter
T_I=0

export LC_ALL=C

echo
echo -n "Checking '/usr/share/ufw/check-requirements -f' ... "
if /usr/share/ufw/check-requirements -f >/dev/null ; then
    echo "[OK]"
    S_I=$(($S_I +1))
else
    echo "!FAIL!"
    F_I=$(($F_I +1))
fi
T_I=$(($T_I +1))

#######################################
# Print summary
echo
echo "ufw kernel requirements tests:"
echo " Passed: ${S_I}/${T_I}"
echo " Failed: ${F_I}/${T_I}"
echo

exit ${F_I}
