#!/bin/bash
################################################################################
# Copyright 2013 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 2.1.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Juhapekka Piiroinen <juhapekka.piiroinen@canonical.com>
#         Jamie Strandboge <jamie@canonical.com>
################################################################################

set -e

# Required packages
PACKAGES="apparmor ufw iptables click-apparmor apparmor-easyprof-ubuntu ubuntu-app-launch"

# Failure counter
F_I=0

# Success counter
S_I=0

# Total counter
T_I=0

#######################################
# Checks for package availability
echo
for PACKAGE in ${PACKAGES}; do
    echo -n "Checking if '${PACKAGE}' is available... "
    FOUND=`apt-cache policy ${PACKAGE}|grep -i candidate|wc -l`
    if [ ${FOUND} -eq 0 ]; then
        echo "!NOT FOUND!"
        F_I=$(($F_I +1))
    else
        echo "[OK]"
        S_I=$(($S_I +1))
    fi
    T_I=$(($T_I +1))
done

#######################################
# Print summary
echo
echo "Availability:"
echo " Found packages: ${S_I}/${T_I}"
echo " Missing packages: ${F_I}/${T_I}"
echo

if [ ${F_I} -gt 0 ]; then
    exit ${F_I}
fi

#######################################
# Reset counters

# Failure counter
F_I=0

# Success counter
S_I=0

# Total counter
T_I=0

#######################################
# Checks for installed packages
echo
for PACKAGE in ${PACKAGES}; do
    echo -n "Checking if '${PACKAGE}' is installed... "
    FOUND=`apt-cache policy ${PACKAGE}|egrep -i '  Installed:' | grep -v '(' | wc -l`
    if [[ ${FOUND} -eq 0 ]]; then
        echo "!NOT FOUND!"
        F_I=$(($F_I +1))
    else
        echo "[OK]"
        S_I=$(($S_I +1))
    fi
    T_I=$(($T_I +1))
done

#######################################
# Print summary
echo
echo "Installed:"
echo " Found packages: ${S_I}/${T_I}"
echo " Missing packages: ${F_I}/${T_I}"
echo

exit ${F_I}
